created the five models: events, users, caterers, hosts, subscribers
velvelshteynberg/TorontoEvents pull request #3
Opened 2021-08-16 01:49 UTC by velvelshteynberg

Created the five models: events, users, caterers, hosts, subscribers. 
Also did some config work with Sree. 

Please review and approve. 
Thanks

2021-08-16 02:05 UTC, Shane0018 requested changes
for the columns t.boolean :approved
      t.boolean :require_update
t.boolean :subscribe
      t.boolean :admin

2021-08-16 15:18 UTC, velvelshteynberg commented
Good morning 
I changed 3 of the column names. I didn't change the admin column name because I think it should be called admin because we will just assign a true/false value. 
Please review and approve or let me know what other updates I should work on. 
Thanks

2021-08-16 23:48 UTC, Shoshana01 commented on db/migrate/20210816014222_create_users.rb
> +      t.string :phone
shouldnt phone be integer?

2021-08-16 23:51 UTC, Shoshana01 requested changes
Looks good to me besides I think the phone number columns should be of type integer

2021-08-17 13:22 UTC, velvelshteynberg commented
During development of the data modeling we decided that phone number are strings and that is what I am going based on. 
Please review and approve. 
Thanks

2021-08-17 19:16 UTC, Shoshana01 approved these changes

2021-08-17 23:48 UTC, merged